
import { Deal } from "@/types/deal";
import restaurantBurger from "@/assets/deals/restaurant-burger.jpg";
import electronicsTech from "@/assets/deals/electronics-tech.jpg";
import coffeeCafe from "@/assets/deals/coffee-cafe.jpg";
import homeAppliances from "@/assets/deals/home-appliances.jpg";
import dessertBakery from "@/assets/deals/dessert-bakery.jpg";
import spaWellness from "@/assets/deals/spa-wellness.jpg";
import fitnessGym from "@/assets/deals/fitness-gym.jpg";
import fashionClothing from "@/assets/deals/fashion-clothing.jpg";

// Demo images for different deal categories
const dealImages = {
  restaurant: restaurantBurger,
  electronics: electronicsTech,
  coffee: coffeeCafe,
  appliances: homeAppliances,
  dessert: dessertBakery,
  spa: spaWellness,
  fitness: fitnessGym,
  fashion: fashionClothing,
};

// Enhanced deals array with realistic examples and proper demo images
export const deals: Deal[] = [
  {
    id: 1,
    title: "Gourmet Burger Combo - 40% Off",
    description: "Enjoy our signature gourmet burger with crispy fries and a drink. Perfect for a satisfying meal with friends and family.",
    image: dealImages.restaurant,
    originalPrice: 1200,
    discountedPrice: 720,
    discount: 40,
    category: "Food & Dining",
    tags: ["burger", "restaurant", "combo", "gourmet"],
    location: "12 MG Road, Andheri West",
    city: "Mumbai",
    phone: "+91 9876543210",
    expiryDate: "2025-05-31",
    rating: 4.5,
    featured: true,
    duration: 7,
  },
  {
    id: 2,
    title: "Latest Smartphones & Laptops - 50% Off",
    description: "Huge electronics sale on premium smartphones, laptops, and accessories. Limited time offer on select models.",
    image: dealImages.electronics,
    originalPrice: 25000,
    discountedPrice: 12500,
    discount: 50,
    category: "Shopping",
    tags: ["electronics", "smartphone", "laptop", "technology"],
    location: "42 Tech Plaza, Koramangala",
    city: "Bangalore",
    phone: "+91 9988776655",
    expiryDate: "2025-06-07",
    rating: 4.2,
    featured: true,
    duration: 15,
  },
  {
    id: 3,
    title: "Artisan Coffee & Pastries - Buy 1 Get 1 Free",
    description: "Freshly brewed artisan coffee with handmade pastries. Perfect spot for your morning coffee or evening hangout.",
    image: dealImages.coffee,
    originalPrice: 400,
    discountedPrice: 200,
    discount: 50,
    category: "Food & Dining",
    tags: ["coffee", "cafe", "pastries", "artisan", "bogo"],
    location: "101 Connaught Place, Central Delhi",
    city: "Delhi",
    phone: "+91 9876543100",
    expiryDate: "2025-05-28",
    rating: 4.8,
    featured: true,
    duration: 3,
  },
  {
    id: 4,
    title: "Premium Home Appliances - 30% Off",
    description: "Upgrade your home with energy-efficient appliances. Latest models with warranty and free installation.",
    image: dealImages.appliances,
    originalPrice: 8000,
    discountedPrice: 5600,
    discount: 30,
    category: "Shopping",
    tags: ["appliances", "home", "kitchen", "energy-efficient"],
    location: "99 Express Avenue, Anna Nagar",
    city: "Chennai",
    phone: "+91 9900112233",
    expiryDate: "2025-06-10",
    rating: 4.1,
    featured: false,
    duration: 10,
  },
  {
    id: 5,
    title: "Luxury Dessert Platter - Free with Main Course",
    description: "Indulge in our exquisite dessert collection. Get a complimentary luxury dessert platter with any main course.",
    image: dealImages.dessert,
    originalPrice: 1200,
    discountedPrice: 1200,
    discount: 0,
    category: "Food & Dining",
    tags: ["dessert", "luxury", "free", "main course"],
    location: "50 Park Street, Park Circus",
    city: "Kolkata",
    phone: "+91 9123456789",
    expiryDate: "2025-05-30",
    rating: 4.6,
    featured: false,
    duration: 5,
  },
  {
    id: 6,
    title: "Relaxing Spa Package - 60% Off",
    description: "Unwind with our premium spa treatments including full body massage, facial, and aromatherapy session.",
    image: dealImages.spa,
    originalPrice: 3500,
    discountedPrice: 1400,
    discount: 60,
    category: "Health & Beauty",
    tags: ["spa", "massage", "wellness", "relaxation", "beauty"],
    location: "15 Spa Gardens, Banjara Hills",
    city: "Hyderabad",
    phone: "+91 9876541234",
    expiryDate: "2025-06-15",
    rating: 4.7,
    featured: true,
    duration: 12,
  },
  {
    id: 7,
    title: "Fitness Gym Membership - 3 Months Free",
    description: "Join our state-of-the-art fitness center with modern equipment, personal training, and group classes.",
    image: dealImages.fitness,
    originalPrice: 4500,
    discountedPrice: 1500,
    discount: 67,
    category: "Health & Beauty",
    tags: ["gym", "fitness", "membership", "training", "health"],
    location: "88 Fitness Complex, Sector 17",
    city: "Pune",
    phone: "+91 9988445566",
    expiryDate: "2025-06-20",
    rating: 4.3,
    featured: false,
    duration: 20,
  },
  {
    id: 8,
    title: "Trendy Fashion Collection - 45% Off",
    description: "Latest fashion trends for men and women. Designer clothing, accessories, and footwear at unbeatable prices.",
    image: dealImages.fashion,
    originalPrice: 2500,
    discountedPrice: 1375,
    discount: 45,
    category: "Shopping",
    tags: ["fashion", "clothing", "designer", "trendy", "accessories"],
    location: "22 Fashion Street, Commercial Street",
    city: "Bangalore",
    phone: "+91 9876567890",
    expiryDate: "2025-06-05",
    rating: 4.4,
    featured: true,
    duration: 8,
  },
  {
    id: 9,
    title: "Weekend Brunch Special - 35% Off",
    description: "All-you-can-eat brunch buffet with continental and Indian delicacies. Perfect for family weekend outings.",
    image: dealImages.restaurant,
    originalPrice: 1500,
    discountedPrice: 975,
    discount: 35,
    category: "Food & Dining",
    tags: ["brunch", "buffet", "weekend", "family", "continental"],
    location: "77 Marine Drive, Nariman Point",
    city: "Mumbai",
    phone: "+91 9876098765",
    expiryDate: "2025-06-12",
    rating: 4.5,
    featured: false,
    duration: 14,
  },
  {
    id: 10,
    title: "Premium Coffee Beans - 40% Off",
    description: "Freshly roasted premium coffee beans from around the world. Perfect for home brewing enthusiasts.",
    image: dealImages.coffee,
    originalPrice: 800,
    discountedPrice: 480,
    discount: 40,
    category: "Food & Dining",
    tags: ["coffee", "beans", "premium", "fresh", "home brewing"],
    location: "33 Coffee Lane, Hauz Khas",
    city: "Delhi",
    phone: "+91 9876543987",
    expiryDate: "2025-05-25",
    rating: 4.6,
    featured: false,
    duration: 6,
  },
  {
    id: 11,
    title: "Complete Car Service - 25% Off",
    description: "Full car servicing including oil change, filter replacement, and 50-point inspection by certified mechanics.",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1932&q=80",
    originalPrice: 5000,
    discountedPrice: 3750,
    discount: 25,
    category: "Automotive",
    tags: ["car", "service", "maintenance", "mechanic"],
    location: "45 Auto Hub, Viman Nagar",
    city: "Pune",
    phone: "+91 9876512345",
    expiryDate: "2025-06-25",
    rating: 4.5,
    featured: true,
    duration: 14,
  },
  {
    id: 12,
    title: "Organic Grocery Box - 20% Off",
    description: "Weekly subscription box with fresh organic vegetables, fruits, and dairy products delivered to your doorstep.",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1774&q=80",
    originalPrice: 1800,
    discountedPrice: 1440,
    discount: 20,
    category: "Shopping",
    tags: ["organic", "grocery", "vegetables", "healthy", "delivery"],
    location: "12 Green Market, Anna Nagar",
    city: "Chennai",
    phone: "+91 9876556789",
    expiryDate: "2025-06-30",
    rating: 4.7,
    featured: false,
    duration: 30,
  },
  {
    id: 13,
    title: "Gaming Laptop - ₹15,000 Off",
    description: "High-performance gaming laptop with RTX 4060 graphics, 16GB RAM, and 1TB SSD. Limited stock available!",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?ixlib=rb-4.0.3&auto=format&fit=crop&w=1768&q=80",
    originalPrice: 95000,
    discountedPrice: 80000,
    discount: 16,
    category: "Shopping",
    tags: ["laptop", "gaming", "electronics", "computer"],
    location: "78 Tech Plaza, Nehru Place",
    city: "Delhi",
    phone: "+91 9876598765",
    expiryDate: "2025-06-08",
    rating: 4.3,
    featured: true,
    duration: 7,
  },
  {
    id: 14,
    title: "Couple's Spa Day - 50% Off",
    description: "Romantic spa package for two including full body massage, facial, and champagne with chocolates.",
    image: dealImages.spa,
    originalPrice: 7000,
    discountedPrice: 3500,
    discount: 50,
    category: "Health & Beauty",
    tags: ["spa", "couple", "romantic", "massage", "wellness"],
    location: "22 Wellness Avenue, Jubilee Hills",
    city: "Hyderabad",
    phone: "+91 9876523456",
    expiryDate: "2025-06-14",
    rating: 4.9,
    featured: true,
    duration: 10,
  },
  {
    id: 15,
    title: "Photography Session - 35% Off",
    description: "Professional photoshoot session with 50 edited photos. Perfect for portraits, family, or pre-wedding shoots.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=1938&q=80",
    originalPrice: 8000,
    discountedPrice: 5200,
    discount: 35,
    category: "Services",
    tags: ["photography", "photoshoot", "portrait", "professional"],
    location: "Studio 9, Indiranagar",
    city: "Bangalore",
    phone: "+91 9876534567",
    expiryDate: "2025-06-18",
    rating: 4.6,
    featured: false,
    duration: 15,
  },
  {
    id: 16,
    title: "Pizza Party Pack - Buy 2 Get 1 Free",
    description: "Large pizzas with your choice of toppings. Perfect for parties and family gatherings!",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&auto=format&fit=crop&w=1781&q=80",
    originalPrice: 1800,
    discountedPrice: 1200,
    discount: 33,
    category: "Food & Dining",
    tags: ["pizza", "party", "family", "italian", "bogo"],
    location: "55 Food Court, Park Street",
    city: "Kolkata",
    phone: "+91 9876545678",
    expiryDate: "2025-06-10",
    rating: 4.4,
    featured: false,
    duration: 7,
  },
  {
    id: 17,
    title: "Annual Gym Membership - 40% Off",
    description: "Full access to state-of-the-art gym with personal training, group classes, and nutrition consultation.",
    image: dealImages.fitness,
    originalPrice: 36000,
    discountedPrice: 21600,
    discount: 40,
    category: "Health & Beauty",
    tags: ["gym", "fitness", "membership", "training", "annual"],
    location: "FitZone Complex, Sector 17",
    city: "Pune",
    phone: "+91 9876567123",
    expiryDate: "2025-07-01",
    rating: 4.5,
    featured: true,
    duration: 30,
  },
  {
    id: 18,
    title: "Book Cafe Membership - 30% Off",
    description: "Monthly membership with unlimited coffee refills, book borrowing, and access to quiet reading zones.",
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?ixlib=rb-4.0.3&auto=format&fit=crop&w=1770&q=80",
    originalPrice: 1500,
    discountedPrice: 1050,
    discount: 30,
    category: "Food & Dining",
    tags: ["cafe", "books", "coffee", "membership", "reading"],
    location: "15 Literary Lane, Salt Lake",
    city: "Kolkata",
    phone: "+91 9876578901",
    expiryDate: "2025-06-22",
    rating: 4.8,
    featured: false,
    duration: 20,
  },
  {
    id: 19,
    title: "Designer Saree Collection - 55% Off",
    description: "Exclusive designer sarees in silk and georgette. Perfect for weddings and special occasions.",
    image: dealImages.fashion,
    originalPrice: 12000,
    discountedPrice: 5400,
    discount: 55,
    category: "Shopping",
    tags: ["saree", "designer", "fashion", "wedding", "ethnic"],
    location: "88 Fashion Street, Commercial Street",
    city: "Bangalore",
    phone: "+91 9876589012",
    expiryDate: "2025-06-15",
    rating: 4.7,
    featured: true,
    duration: 12,
  },
  {
    id: 20,
    title: "Home Deep Cleaning - 45% Off",
    description: "Professional deep cleaning service for your entire home. Includes kitchen, bathrooms, and all rooms.",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?ixlib=rb-4.0.3&auto=format&fit=crop&w=1770&q=80",
    originalPrice: 4500,
    discountedPrice: 2475,
    discount: 45,
    category: "Services",
    tags: ["cleaning", "home", "deep clean", "professional", "service"],
    location: "CleanPro Services, Bandra",
    city: "Mumbai",
    phone: "+91 9876590123",
    expiryDate: "2025-06-20",
    rating: 4.4,
    featured: false,
    duration: 10,
  },
];

// Util to add a new deal (used in DealUploadForm)
export function addDeal(deal: Deal) {
  const existing = localStorage.getItem("userDeals");
  let userDeals: Deal[] = [];
  if (existing) {
    try {
      userDeals = JSON.parse(existing);
    } catch (e) {
      userDeals = [];
    }
  }
  userDeals.push(deal);
  localStorage.setItem("userDeals", JSON.stringify(userDeals));
  
  // Trigger real-time notification for new deal
  const event = new CustomEvent('newDealAdded', { 
    detail: { deal } 
  });
  window.dispatchEvent(event);
}

